import Head from 'next/head'

import Navbar from '../components/Navbar'
import Header from '../components/LandingHeader'
import Projects from '../components/Projects'
import Services from '../components/Services'
import Contact from '../components/Contact'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div>
      <div className='bg-slate-900'>
        <Head>
          <title>Samuel Abu | Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta property="og:url" content="https://sam-portfolio-alpha.vercel.app/" />
          <meta property="og:type" content="website" />
          <meta property="og:title" content="Samuel Abu | This is a concise catalog of my deployed projects." key="ogabouttitle" />
          <meta property="og:description" content="I am a Full Stack Web Developer. Feel free to contact me for my services." key="ogaboutdesc" />
          <meta property="og:image" content="https://res.cloudinary.com/dbqn6vejg/image/upload/v1652408526/meta_j5xbkw.jpg" key="ogaboutimg" />

          <meta name="twitter:card" content="summary_large_image" key="twaboutcard"/>
          <meta name="twitter:creator" content="@reachmhp"/>
          <meta name="twitter:creator" content="@reachmhp" />
          <meta property="twitter:domain" content="tunesketch.com"/>
          <meta property="twitter:url" content="https://sam-portfolio-alpha.vercel.app/"/>
          <meta name="twitter:title" content="Samuel Abu | This is a concise catalog of my deployed projects." key="twabouttitle" />
          <meta name="twitter:description" content="I am a Full Stack Web Developer. Feel free to contact me for my services" key="twaboutdesc" />
          <meta name="twitter:image" content="https://res.cloudinary.com/dbqn6vejg/image/upload/v1652408526/meta_j5xbkw.jpg" key="twaboutimg" />
        </Head>
        
          <Navbar />
          <Header />
          <Projects />
          <Services />
          <Contact />
          <Footer />
      </div>
    </div>
  )
}
