import Head from 'next/head'

import Navbar from '../components/Navbar'
import Header from '../components/LandingHeader'
import Projects from '../components/Projects'
import Services from '../components/Services'
import Contact from '../components/Contact'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div>
      <div className='bg-slate-900'>
        <Head>
          <title>Samuel Abu | Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
          <Navbar />
          <Header />
          <Projects />
          <Services />
          <Contact />
          <Footer />
      </div>
    </div>
  )
}
